### ISSUE TITLE
moesif gunicorn heroku

### ISSUE THREAD

**Issue by Tokukawa** [Moesif/moesifwsgi#13]
I tried to deploy moesif on a herokuapp with gunicorn.
The server respond 500 at every request.

**Comment by dgilling** [comment]
Sorry, you’re having trouble. Can you take a screenshot or do you have a log trace?

Derric

**Comment by dgilling** [comment]
@Tokukawa We fixed the issue in 1.1.13. Sorry about the issues. It was due to a change in how we capture IP Address.
